version: '3'
services:
  rabbitmq:
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=callrec
      - RABBITMQ_DEFAULT_PASS=callrec
    ports:
      - "5672:5672"
      - "15672:15672"

