version: '3'
services:
  solr:
    image: solr
    ports:
      - "8983:8983"
    volumes:
      - products:/home/dmytro/dev/tools/volumes/solr/products
  rabbitmq:
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=pass
    ports:
      - "5672:5672"
      - "15672:15672"
volumes:
  products:
    external: true

