version: '3'
services:
  activemq:
    image: rmohr/activemq:latest
    container_name: 'activemq'
    ports:
      - "61616:61616" # broker (admin:adminactivemq)(amq:amq)
      - "8161:8161"   # web    http://boot2docker:8161/admin (admin:admin)
#    volumes:
#      - ~/dev/volumes/data:/data/activemq
#      - ~/dev/volumes/log:/var/log/activemq

  solr:
    image: solr
    ports:
      - "8983:8983"
    volumes:
      - products:/home/dmytro/dev/tools/volumes/solr/products
  rabbitmq:
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=pass
    ports:
      - "5672:5672"
      - "15672:15672"
volumes:
  products:
    external: true

