#- direct

###
GET http://localhost:8081/send/direct/myValue

###
GET http://localhost:8081/sendToTopicExchangeFirst

###
GET http://localhost:8081/sendToTopicExchangeSecond

###
GET http://localhost:8081/sendToTopicExchangeMulti

###
GET http://localhost:8081/sendFanout

###
GET http://localhost:8081/sendHeaders

###
GET http://localhost:8081/get

###
GET http://localhost:8081/find

###
GET http://localhost:8081/findByCriteria

###
GET http://localhost:8983/solr/products/select?indent=true&q=*:*&start=0&rows=20&fq=(id:dimaId+OR+id:dimaId)&fq=(name:dimavalue+OR+name:dimavalue)

###
GET http://localhost:8081/save/333/333333

###
GET http://localhost:8081/save/337773/333588577333

###
GET http://localhost:8081/save/dimaId/dimavalue

###
http://localhost:8081/entity/all



#camel
###
POST http://localhost:8081/camel/api/bean
Content-Type: application/json

{
  "id": 999,
  "name": "beansname"
}



