ALTER DOMAIN WBSC.QUESTIONFORM_SORTING_DOMAIN DROP CONSTRAINT QUESTIONFORM_SORTING_SWITCH;
ALTER DOMAIN WBSC.QUESTIONFORM_SORTING_DOMAIN ADD CONSTRAINT QUESTIONFORM_SORTING_SWITCH CHECK (VALUE = ANY (ARRAY['CREATION_TIME', 'MANUAL', 'WEIGHT_ASC', 'WEIGHT_DESC']));
