server:
  port: 8081

camel:
  springboot:
    name: ServicesRest
management:
  port: 8082
endpoints:
  enabled: false
  health:
    enabled: true
quickstart:
  generateOrderPeriod: 10s
  processOrderPeriod: 30s
app:
  api:
    path: '/camel'

spring:
  rabbitmq:
    username: "user"
    password: "pass"
