-- CREATE FUNCTION GET_CURR__ID {{{
CREATE OR REPLACE FUNCTION callrec.GET_CURR__ID(VARCHAR)
  RETURNS INTEGER
  VOLATILE
  RETURNS NULL ON NULL INPUT
  LANGUAGE plpgsql
  AS '
    DECLARE
      _seq VARCHAR DEFAULT ''callrec.'' || $1;
    BEGIN
      RETURN CAST(CURRVAL(_seq) AS INTEGER);
    END;
  ';
-- }}}

