-- CREATE FUNCTION GET_NEXT__ID {{{
CREATE OR REPLACE FUNCTION callrec.GET_NEXT__ID(VARCHAR)
  RETURNS INTEGER
  VOLATILE
  RETURNS NULL ON NULL INPUT
  LANGUAGE plpgsql
  AS '
    DECLARE
      _seq VARCHAR DEFAULT ''callrec.'' || $1;
    BEGIN
      RETURN CAST(NEXTVAL(_seq) AS INTEGER);
    END;
  ';
-- }}}

