-- CREATE FUNCTION IS_LOCALABSPATH {{{
CREATE OR REPLACE FUNCTION callrec.IS_LOCALABSPATH(VARCHAR)
  RETURNS BOOL
  IMMUTABLE
  RETURNS NULL ON NULL INPUT
  LANGUAGE plpgsql
  AS '
    BEGIN
      RETURN $1 ~ ''^/[^;/]+(/[^;/]+)+$'';
    END;
  ';

GRANT EXECUTE ON FUNCTION callrec.IS_LOCALABSPATH(VARCHAR) TO GROUP callrecgrp;
-- }}}

