-- CREATE FUNCTION GET_CURR_FILTERID {{{
CREATE OR REPLACE FUNCTION callrec.GET_CURR_FILTERID()
  RETURNS callrec.filters.id%TYPE
  VOLATILE
  SECURITY DEFINER
  LANGUAGE plpgsql
  AS '
    BEGIN
      RETURN callrec.GET_CURR__ID(''seq_filters'');
    END;
  ';

GRANT EXECUTE ON FUNCTION callrec.GET_CURR_FILTERID() TO GROUP callrecgrp;
-- }}}

