CREATE OR REPLACE FUNCTION callrec.IS_MD5(VARCHAR)
RETURNS BOOLEAN
IMMUTABLE
RETURNS NULL ON NULL INPUT
LANGUAGE sql
AS $$
    SELECT $1 ~ '(?x)^[[:xdigit:]]{32}$';
$$;

GRANT EXECUTE ON FUNCTION callrec.IS_MD5(VARCHAR) TO GROUP callrecgrp;
