services:
  keycloak:
    ports:
      - '18080:8080'
    environment:
      - DB_DATABASE=keycloak
      - DB_PASSWORD=keycloak
      - DB_USER=keycloak
      - DB_VENDOR=postgres
      - DB_ADDR=jdbc:postgresql://zoom_postgres:5432/keycloak
      - ENABLE_INTERNATIONALIZATION=true
      - JAVA_OPTS=-server
      - KEYCLOAK_DEFAULT_THEME=eleveo
      - KEYCLOAK_PASSWORD=password
      - KEYCLOAK_USER=admin
      - KEYCLOAK_VERSION=16.1.0-19.0.4
      - KEYCLOAK_WELCOME_THEME=eleveo
      - MASTER_CLIENT_DEFAULT_ROLES=manage-clients,manage-users,view-realm
      - MASTER_CLIENT_NAME=client-management-app
      - MASTER_CLIENT_SECRET=password
      - MESSAGE_QUEUE_HOST=rabbitmq-kc
      - MESSAGE_QUEUE_PASSWORD=guest
      - MESSAGE_QUEUE_PORT=5673
      - MESSAGE_QUEUE_USERNAME=guest
      - ROOT_LOGLEVEL=INFO
      - SMTP_FROM=keycloak.server@zoomint.com
      - SMTP_HOST=172.17.0.4
      - SMTP_PASSWORD=password
      - SMTP_PORT=1025
      - SMTP_USERNAME=any
      - X509_CA_BUNDLE=/zoom-ca-bundle.crt
      - ZQM_VERSION=ic_do_rici
      - 'true'
    container_name: zoom_keycloak
    hostname: keycloak
    depends_on:
      - rabbitmq-kc
      - postgres
    image: 'artifactory.zoomint.com/zoomint/keycloak:16.1.0-19.0.4'
  kcproxy:
    ports:
      - '18081:8080'
    environment:
      - KEYCLOAK_HOST=zoom_keycloak
      - KEYCLOAK_PORT=8080
      - KEYCLOAK_PROXY_PORT=8080
      - MESSAGE_QUEUE_HOST=rabbitmq-kc
    container_name: KC-Proxy
    hostname: kcproxy
    depends_on:
      - rabbitmq-kc
      - keycloak
      - postgres
    image: 'artifactory.zoomint.com/zoomint/keycloak-api-proxy:1.18.0'
  rabbitmq:
    ports:
      - '15672:15672'
      - '5672:5672'
    environment:
      - RABBITMQ_DEFAULT_PASS=callrec
      - RABBITMQ_DEFAULT_USER=callrec
    container_name: RabbitMQ
    hostname: rabbitmq
    image: 'rabbitmq:management'
  rabbitmq-kc:
    ports:
      - '15673:15672'
      - '5673:5672'
    environment:
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_USER=guest
    container_name: RabbitMQ-KC
    hostname: rabbitmq-kc
    image: 'rabbitmq:3-management'
  solr:
    ports:
      - '9983:9983'
      - '8983:8983'
    image: 'zoomint/zoomint-solr-cloud:7.6.0.15'
    container_name: 'zoom_solr'
  postgres:
    container_name: 'zoom_postgres'
    image: 'postgres:9.6'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DATABASE=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
    external: true


# keycloak
#  docker run --rm -e KEYCLOAK_USER=admin -e KEYCLOAK_PASSWORD=password -it --hostname zoom-keycloak -p 443:443  localhost:5000/zoomint/keycloak:16.1.0-19.6.0

# postgres
#  docker run -p 5432:5432 -e POSTGRES_PASSWORD=postgres -e POSTGRES_DATABASE=postgres -e POSTGRES_DB=postgres -e POSTGRES_USER=postgres --rm -v pgdata:/var/lib/postgresql/data --name postgres_zoom postgres:9.6

# rabbit
#  docker run --rm -e RABBITMQ_DEFAULT_USER=callrec -e RABBITMQ_DEFAULT_PASS=callrec -it --hostname zoom-rabbit -p 15672:15672 -p 5672:5672 rabbitmq:management

# solr
#  docker run -p 8983:8983 -p 9983:9983 --rm --name zoom_solr zoomint/zoomint-solr-cloud:7.6.0.15