ALTER TABLE WBSC.SUBEVALUATION ADD COLUMN MAX_POSSIBLE_TOTAL NUMERIC(12,6);
ALTER TABLE WBSC.SUBEVALUATION ADD COLUMN SUCCESS_RATE NUMERIC(12,6);
ALTER TABLE WBSC.EVALUATIONS ADD COLUMN MAX_POSSIBLE_TOTAL NUMERIC(12,6);
ALTER TABLE WBSC.EVALUATIONS ADD COLUMN SUCCESS_RATE NUMERIC(12,6);
ALTER TABLE wbsc.EVALUATIONS ADD COLUMN METHOD_USED CHARACTER VARYING;
