CREATE TRIGGER trigdel
  AFTER DELETE ON callrec.couples
  FOR EACH ROW EXECUTE PROCEDURE callrec.TRIG_COUPLES_AFTER_DELETE();

CREATE TRIGGER trigdel_before
  BEFORE DELETE ON callrec.couples
  FOR EACH ROW EXECUTE PROCEDURE callrec.TRIG_COUPLES_BEFORE_DELETE();

